name: Java CI
on: [ push, pull_request ]

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_PAT }}
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dotmatthew'
      - name: Install plugins
        run: npm install semantic-release@25.0.2 @semantic-release/github @dotmatthew/semantic-release-config@1.0.0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_GITHUB_PAT }}
      - name: Bump version if necessary
        run: npx semantic-release --extends @dotmatthew/semantic-release-config
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_PAT }}

