name: Java CI
on: [ push, pull_request ]

permissions:
  contents: write
  packages: write
  issues: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install plugins
        run: npm install @semantic-release/git @semantic-release/gitlab @semantic-release/exec semantic-release-monorepo
      - name: Bump version if necessary
        run: npx semantic-release

