name: Matrix-strategy
on:
  workflow_dispatch:
    inputs:
      env:
        description: "In which environment should be deployed"
        required: true
        type: choice
        default: 'INT'
        options:
          - INT
          - PROD

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      web-ips: ${{ steps.web-server-addresses.web-ips }}
      app-ips: ${{ steps.app-server-addresses.app-ips }}
    steps:
      - name: Set web server addresses
        id: web-server-addresses
        run: |
          echo 'web-ips=[${{ vars.WEB_SERVER_ADDRESSES }}]' >> "$GITHUB_OUTPUT"
      - name: Set application server addresses
        id: app-server-addresses
        run: |
          echo 'app-ips=[${{ vars.APP_SERVER_ADDRESSES }}]' >> "$GITHUB_OUTPUT"

  matrix-job-web-server:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        web-ips: ${{ needs.setup.outputs.web-ips }}

    steps:
      - name: Print ips
        run: |
          echo ${{ matrix.web-ips }}

  matrix-job-app-server:
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        app-ips: ${{ needs.setup.outputs.app-ips }}

    steps:
      - name: Print ips
        run: |
          echo ${{ matrix.app-ips }}
