name: release-workflow.yml
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  maven-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set mvn version
        run: mvn versions:set -DnewVersion="${{ github.ref_name }}"
      - name: Publish package to github registry
        run: mvn -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate against ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image with latest tag
        run: |
          docker build -t ghcr.io/dotmatthew/github-action-tests:latest .
      - name: build image with version tag
        if: ${{ env.NEXT_VERSION != '' }}
        run: |
          docker tag ghcr.io/dotmatthew/github-action-tests:latest \
          ghcr.io/dotmatthew/github-action-tests:${{ github.ref_name }}
      - name: push to docker registry
        run: |
          docker push --all-tags ghcr.io/dotmatthew/github-action-tests
