name: test-workflow.yml
on:
  push:
    paths-ignore:
      - .github/**

jobs:
  reusable-workflow:
    uses: dotMatthew/github-actions-reusable-workflows/.github/workflows/example-workflow.yml@main

